// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:takion/src/data/dto/dto.dart';
import 'package:takion/src/domain/entities/entities.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(IssueDetailsCreditDtoAdapter());
    registerAdapter(IssueDetailsCreditRoleDtoAdapter());
    registerAdapter(IssueDetailsDtoAdapter());
    registerAdapter(IssueDetailsNamedRefDtoAdapter());
    registerAdapter(IssueDetailsParticipationDtoAdapter());
    registerAdapter(IssueDetailsReprintDtoAdapter());
    registerAdapter(IssueDetailsSeriesDtoAdapter());
    registerAdapter(IssueDetailsVariantDtoAdapter());
    registerAdapter(IssueListDtoAdapter());
    registerAdapter(IssueListSeriesDtoAdapter());
    registerAdapter(ItemRoleAdapter());
    registerAdapter(ListContentTypeAdapter());
    registerAdapter(ReadingListAdapter());
    registerAdapter(ReadingListItemAdapter());
    registerAdapter(SeriesDtoAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(IssueDetailsCreditDtoAdapter());
    registerAdapter(IssueDetailsCreditRoleDtoAdapter());
    registerAdapter(IssueDetailsDtoAdapter());
    registerAdapter(IssueDetailsNamedRefDtoAdapter());
    registerAdapter(IssueDetailsParticipationDtoAdapter());
    registerAdapter(IssueDetailsReprintDtoAdapter());
    registerAdapter(IssueDetailsSeriesDtoAdapter());
    registerAdapter(IssueDetailsVariantDtoAdapter());
    registerAdapter(IssueListDtoAdapter());
    registerAdapter(IssueListSeriesDtoAdapter());
    registerAdapter(ItemRoleAdapter());
    registerAdapter(ListContentTypeAdapter());
    registerAdapter(ReadingListAdapter());
    registerAdapter(ReadingListItemAdapter());
    registerAdapter(SeriesDtoAdapter());
  }
}
