// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:takion/src/data/models/issue_dto.dart';
import 'package:takion/src/data/models/series_dto.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(IssueDtoAdapter());
    registerAdapter(SeriesDtoAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(IssueDtoAdapter());
    registerAdapter(SeriesDtoAdapter());
  }
}
